name: 部署gh-pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMMIT_SECRET: ${{secrets.COMMIT_SECRET}}
      USER_NAME: github-actions
      USER_EMAIL: github-actions@github.com
      WORK_DIR: ./gh-pages
      PUBLISH_DIR: ./gh-pages/dist
      BRANCH: gh-pages
    steps:
      - uses: actions/checkout@v2

#      - name: Cache node modules
#        uses: actions/cache@v2
#        env:
#          cache-name: cache-node-modules
#        with:
#          path: ~/.npm
#          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#          restore-keys: |
#            ${{ runner.os }}-node-

      - name: 变量
        run: |
          echo $USER_NAME $USER_EMAIL $WORK_DIR $PUBLISH_DIR $BRANCH

      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          check-latest: true
      - name: 安装依赖
        working-directory: $WORK_DIR
        run: npm install
      - name: 编译html
        working-directory: $WORK_DIR
        run: npm run generate:gh-pages
      - name: 提交到GitHub pages
        run: |
          cd $PUBLISH_DIR
          echo ===files===
          ls
          echo ===files===
          git init
          git config user.name $USER_NAME
          git config user.email $USER_EMAIL
          git remote add origin https://$COMMIT_SECRET@github.com/$GITHUB_REPOSITORY.git
          git checkout -b gh-pages
          git add --all
          git status
          git commit -m "Github Action自动编译"
          git push origin gh-pages -f