name: 部署gh-pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMMIT_SECRET: ${{secrets.COMMIT_SECRET}}
      USER_NAME: github-actions
      USER_EMAIL: github-actions@github.com
      PUBLISH_DIR: ./gh-page/dist
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          # check-latest: true
      - name: 安装依赖
        working-directory: './gh-page'
        run: npm install
      - name: 编译html
        working-directory: './gh-page'
        run: npm run generate:gh-pages
      - name: 提交到GitHub pages
        run: |
          cd $PUBLISH_DIR
          ls
          git init
          git config user.name $USER_NAME
          git config user.email $USER_EMAIL
          git status
          git remote add origin https://$MY_SECRET@github.com/$GITHUB_REPOSITORY.git
          git checkout -b gh-pages
          git add ./
          git commit -m "Github Action自动编译"
          git push